### ISSUE TITLE
Custom annotations in VEP example

### ISSUE THREAD

**Issue by geocarvalho** [josephhalstead/pyvariantfilter#2]
Hello, thanks for the project!
I'd like to know if the custom annotation files from gnomad used by you are the files available ones on the [website]:(https://gnomad.broadinstitute.org/downloads)

Genome: All chromosomes VCF (.tbi)
460.93 GiB, MD5: e6eadf5ac7b2821b40f350da6e1279a2

Exome: All chromosomes VCF (.tbi)
58.81 GiB, MD5: f034173bf6e57fbb5e8ce680e95134f2

Best regards!

**Comment by josephhalstead** [comment]
Hi,

Sorry just seen this!

Yep - I used the ones from gnomad rather than the ones bundled with VEP. I used an older version of gnomad in this analysis 2.0.1 rather than 2.1.1
